name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...

    - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        mkdir -p dist/monte-carlo-exploration
        go build -o dist/monte-carlo-exploration .

    - name: Prepare distribution
      run: |
        cp README.md dist/monte-carlo-exploration
        cp LICENSE dist/monte-carlo-exploration
        cp -r examples dist/monte-carlo-exploration

    - name: Upload for ${{ matrix.goos }}/${{ matrix.goarch }}
      uses: actions/upload-artifact@v2
      with:
        name: monte-carlo-exploration-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/monte-carlo-exploration
